### ISSUE TITLE
npm install | Error: self-signed certificate in certificate chain

### ISSUE THREAD

**Issue by pfeilbr** [elfvingralf/macOSpilot-ai-assistant#1]
`npm install` yields the following error on my system:

npm ERR! code 1
npm ERR! path /Users/pfeilbr/projects/macOSpilot-ai-assistant/node_modules/ffmpeg-static
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Error: self-signed certificate in certificate chain
npm ERR!     at TLSSocket.onConnectSecure (node:_tls_wrap:1550:34)
npm ERR!     at TLSSocket.emit (node:events:514:28)
npm ERR!     at TLSSocket._finishInit (node:_tls_wrap:967:8)
npm ERR!     at ssl.onhandshakedone (node:_tls_wrap:743:12) {
npm ERR!   code: 'SELF_SIGNED_CERT_IN_CHAIN'
npm ERR! }

<img width="579" alt="image" src="https://github.com/elfvingralf/macOSpilot-ai-assistant/assets/1968/ae91feb9-3727-4bc2-b2a3-b30c826e0c42">

<img width="279" alt="image" src="https://github.com/elfvingralf/macOSpilot-ai-assistant/assets/1968/8fd0b548-628e-4b35-8a1f-0d895f40cc32">

<img width="405" alt="image" src="https://github.com/elfvingralf/macOSpilot-ai-assistant/assets/1968/a5c28c12-880d-4323-8453-0e2e7a80ee3d">

**Comment by JoelBCarter** [comment]
@pfeilbr The repo has a `yarn.lock` file did you try using `yarn install` instead of `npm install`?

**Comment by pfeilbr** [comment]
@JoelBCarter thanks for your response.  tried yarn install, but got same error.  it might be something specific to my machine/openssl.  i'll keep playing around with it.

<img width="571" alt="image" src="https://github.com/elfvingralf/macOSpilot-ai-assistant/assets/1968/e7222b8a-28d7-4675-9459-79b84693ba48">

**Comment by pfeilbr** [comment]
@JoelBCarter this workaround worked and i'm able to run

`NODE_TLS_REJECT_UNAUTHORIZED=0 npm install`
